# fly.toml app configuration file generated for fundr on 2023-06-26T14:51:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fundr"
primary_region = "lhr"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"
  DATABASE_URL="postgres://ben.stell1989:9chrqkCEMe6z@ep-morning-heart-773376.eu-central-1.aws.neon.tech/fundr_prd"
  SECRET_KEY="django-insecure-$57_-_auxvp&*-g*mvkt9hh#mg()+w77z8z)q*!2f+jfpbhgct"
  DEBUG="True"
  AWS_ACCESS_KEY_ID="AKIA6DV752B2LP6TBIVC"
  AWS_SECRET_ACCESS_KEY="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"
  S3_BUCKET="fundr-bucket"
  S3_BASE_URL="https://s3.eu-west-2.amazonaws.com/"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
