# Generated by Django 4.2.2 on 2023-07-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_profile_catchment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.CharField(blank=True, default='https://fundr.fly.dev/static/main_app/home_pic.png', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default='https://fundr.fly.dev/static/main_app/home_pic.png', max_length=200),
        ),
    ]
